replicas: 2

tag: v0.0.4

image: paskalmaksim/ingress-default-backend
imagePullPolicy: IfNotPresent

pdb:
  minAvailable: 1

args: []

resources:
  requests:
    cpu: 10m  
    memory: 100Mi

topologySpreadConstraints:
- maxSkew: 1
  topologyKey: topology.kubernetes.io/zone
  whenUnsatisfiable: DoNotSchedule
  labelSelector:
    matchLabels:
      app: ingress-default-backend

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - ingress-default-backend
      topologyKey: kubernetes.io/hostname