apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-default-backend
spec:
  selector:
    matchLabels:
      app: ingress-default-backend
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: ingress-default-backend
    spec:
{{ if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 7 }}
{{ end }}
{{ if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 7 }}
{{ end }}
{{ if .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
{{ toYaml .Values.topologySpreadConstraints | indent 7 }}
{{ end }}
      affinity:
{{ toYaml .Values.affinity | indent 7 }}
      containers:
      - name: ingress-default-backend
        image: {{ printf "%s/%s:%s" (default .Values.image.registry .Values.global.imageRegistry) .Values.image.repository .Values.image.tag  }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- if .Values.args }}
        args:
{{ toYaml .Values.args | indent 8 }}
{{- end }}
        resources:
{{ toYaml .Values.resources | indent 9 }}
        securityContext:
          runAsNonRoot: true
          runAsUser: 30001
          runAsGroup: 30001
          privileged: false
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
