run:
  timeout: 5m
issues:
  fix: true
linters:
  enable-all: true
  disable:
  - exhaustivestruct
  - varnamelen
  - gochecknoglobals
  - exhaustruct
  - depguard
  - gomnd
  - execinquery
  - exportloopref